export const mockProducts = [
  // 💻 Kompüterlər
  {
    id: "pc1",
    name: "MacBook Pro 14 M3",
    price: 2899,
    image: "/images/macbook-pro.jpg",
    description: "Apple M3 Pro çipi, 16GB RAM, 512GB SSD.",
    category: "komputerler",
  },
  {
    id: "pc2",
    name: "ASUS ROG Strix G15",
    price: 1999,
    image: "/images/ASUS ROG Strix G15.jpeg",
    description: "RTX 4070, Ryzen 9, 144Hz ekran.",
    category: "komputerler",
  },
  {
    id: "pc3",
    name: "Lenovo ThinkPad X1",
    price: 1699,
    image: "/images/Lenovo ThinkPad X1.jpg",
    description: "Yüngül və biznes yönümlü dizayn.",
    category: "komputerler",
  },
  {
    id: "pc4",
    name: "HP Spectre x360",
    price: 1499,
    image: "/images/HP Spectre x360.jpg",
    description: "2-in-1 dizayn, OLED ekran.",
    category: "komputerler",
  },
  {
    id: "pc5",
    name: "MSI GF63 Thin",
    price: 1099,
    image: "/images/MSI GF63 Thin.webp",
    description: "Gaming üçün əlverişli qiymətə.",
    category: "komputerler",
  },
  {
    id: "pc6",
    name: "Dell XPS 13",
    price: 1799,
    image: "/images/Dell XPS 13.jpg",
    description: "Premium hissiyat və güclü performans.",
    category: "komputerler",
  },
  {
    id: "pc7",
    name: "Acer Swift 5",
    price: 999,
    image: "/images/Acer Swift 5.jpg",
    description: "Hafif və tələbələr üçün ideal.",
    category: "komputerler",
  },
  {
    id: "pc8",
    name: "Surface Laptop 5",
    price: 1499,
    image: "/images/Surface Laptop 5.jpg",
    description: "Toxunmatik ekran və zərif dizayn.",
    category: "komputerler",
  },
  {
    id: "pc9",
    name: "Huawei MateBook X Pro",
    price: 1399,
    image: "/images/Huawei MateBook X Pro.jpeg",
    description: "3K ekran, metal gövdə.",
    category: "komputerler",
  },
  {
    id: "pc10",
    name: "Gigabyte AERO 16",
    price: 2299,
    image: "/images/Gigabyte AERO 16.jpg",
    description: "Yaradıcılar üçün 4K OLED laptop.",
    category: "komputerler",
  },

  // 📱 Telefonlar
  {
    id: "ph1",
    name: "iPhone 15 Pro",
    price: 1899,
    image: "/images/iPhone 15 Pro.jpg",
    description: "Titan korpus, A17 çip.",
    category: "telefonlar",
  },
  {
    id: "ph2",
    name: "Samsung Galaxy S24",
    price: 1799,
    image: "/images/Samsung Galaxy S24.webp",
    description: "200MP kamera və S Pen dəstəyi.",
    category: "telefonlar",
  },
  {
    id: "ph3",
    name: "Google Pixel 8 Pro",
    price: 1599,
    image: "/images/Google Pixel 8 Pro.webp",
    description: "Tensor çip, təmiz Android.",
    category: "telefonlar",
  },
  {
    id: "ph4",
    name: "Xiaomi 14 Pro",
    price: 1099,
    image: "/images/Xiaomi 14 Pro.jpg",
    description: "Sürətli şarj və güclü kamera.",
    category: "telefonlar",
  },
  {
    id: "ph5",
    name: "OnePlus 12",
    price: 1199,
    image: "/images/OnePlus12.webp",
    description: "Hızlı performans və 120Hz ekran.",
    category: "telefonlar",
  },
  {
    id: "ph6",
    name: "Honor Magic6",
    price: 999,
    image: "/images/Honor Magic6.png",
    description: "Əlverişli qiymətə flaqman keyfiyyəti.",
    category: "telefonlar",
  },
  {
    id: "ph7",
    name: "Nothing Phone 2",
    price: 949,
    image: "/images/Nothing Phone 2.webp",
    description: "LED arxa dizayn və bənzərsiz UI.",
    category: "telefonlar",
  },
  {
    id: "ph8",
    name: "Samsung Galaxy A54",
    price: 649,
    image: "/images/Samsung Galaxy A54.webp",
    description: "Orta seqmentdə güclü seçim.",
    category: "telefonlar",
  },
  {
    id: "ph9",
    name: "iPhone SE 2022",
    price: 499,
    image: "/images/iPhone SE 2022.jpg",
    description: "Kompakt və güclü A15 çip.",
    category: "telefonlar",
  },
  {
    id: "ph10",
    name: "Realme GT Neo 5",
    price: 599,
    image: "/images/Realme GT Neo 5.webp",
    description: "240W sürətli şarj!",
    category: "telefonlar",
  },

  // 🎧 Aksessuarlar
  {
    id: "acc1",
    name: "Sony WH-1000XM5",
    price: 499,
    image: "/images/Sony WH-1000XM5.jpg",
    description: "Səssə qarşı aktiv izolyasiya.",
    category: "aksessuarlar",
  },
  {
    id: "acc2",
    name: "Apple AirPods Pro 2",
    price: 349,
    image: "/images/Apple AirPods Pro 2.webp",
    description: "ANC və Spatial Audio dəstəyi.",
    category: "aksessuarlar",
  },
  {
    id: "acc3",
    name: "Logitech MX Master 3S",
    price: 129,
    image: "/images/Logitech MX Master 3S.jpg",
    description: "Erqonomik və səssiz klik.",
    category: "aksessuarlar",
  },
  {
    id: "acc4",
    name: "Anker PowerCore 20000",
    price: 79,
    image: "/images/Anker PowerCore 20000.jpg",
    description: "Sürətli şarj edən powerbank.",
    category: "aksessuarlar",
  },
  {
    id: "acc5",
    name: "Samsung Galaxy Watch 6",
    price: 299,
    image: "/images/SamsungGalaxy Watch 6.webp",
    description: "Samsung istifadəçiləri üçün ideal.",
    category: "aksessuarlar",
  },
  {
    id: "acc6",
    name: "Apple Watch SE",
    price: 329,
    image: "/images/Apple Watch SE.webp",
    description: "iPhone ilə inteqrasiya.",
    category: "aksessuarlar",
  },
  {
    id: "acc7",
    name: "JBL Go 3",
    price: 59,
    image: "/images/JBL Go 3.webp",
    description: "Suya davamlı bluetooth dinamik.",
    category: "aksessuarlar",
  },
  {
    id: "acc8",
    name: "Baseus USB Hub",
    price: 39,
    image: "/images/Baseus USB Hub.webp",
    description: "Type-C ilə 6 port çıxış.",
    category: "aksessuarlar",
  },
  {
    id: "acc9",
    name: "Logitech K380",
    price: 79,
    image: "/images/Logitech K380.webp",
    description: "3 cihaz dəstəyi olan bluetooth klaviatura.",
    category: "aksessuarlar",
  },
  {
    id: "acc10",
    name: "Razer Mousepad RGB",
    price: 49,
    image: "/images/Razer Mousepad RGB.jpg",
    description: "RGB işıqlı geniş mousepad.",
    category: "aksessuarlar",
  },

  // 📺 Televizorlar
  {
    id: "tv1",
    name: "LG OLED55C3",
    price: 1499,
    image: "/images/LG OLED55C3.webp",
    description: "OLED texnologiyası, 4K HDR.",
    category: "televizorlar",
  },
  {
    id: "tv2",
    name: "Samsung Neo QLED 65”",
    price: 1899,
    image: "/images/Samsung Neo QLED 65”.png",
    description: "Mini LED texnologiyası ilə super parıltı.",
    category: "televizorlar",
  },
  {
    id: "tv3",
    name: "Sony Bravia XR A80K",
    price: 1799,
    image: "/images/Sony Bravia XR A80K.webp",
    description: "Cognitive Processor XR ilə təbii görüntü.",
    category: "televizorlar",
  },
  {
    id: "tv4",
    name: "TCL C845 55” QLED",
    price: 1199,
    image: "/images/TCL C845 55” QLED.webp",
    description: "Büdcəyə uyğun yüksək keyfiyyət.",
    category: "televizorlar",
  },
  {
    id: "tv5",
    name: "Philips Ambilight 4K",
    price: 1299,
    image: "/images/Philips Ambilight 4K.webp",
    description: "Ambilight işıqlı TV.",
    category: "televizorlar",
  },
  {
    id: "tv6",
    name: "Hisense U8H",
    price: 1099,
    image: "/images/Hisense U8H.webp",
    description: "Dolby Vision və IMAX Enhanced.",
    category: "televizorlar",
  },
  {
    id: "tv7",
    name: "Samsung The Frame",
    price: 1599,
    image: "/images/Samsung The Frame.jpg",
    description: "Dekorativ dizayn və 4K görüntü.",
    category: "televizorlar",
  },
  {
    id: "tv8",
    name: "Xiaomi Mi TV Q1",
    price: 899,
    image: "/images/Xiaomi Mi TV Q1.webp",
    description: "Əla qiymətə 120Hz 4K TV.",
    category: "televizorlar",
  },
  {
    id: "tv9",
    name: "LG NanoCell 65”",
    price: 1399,
    image: "/images/LG NanoCell 65.png",
    description: "Canlı rənglər və smart TV funksiyaları.",
    category: "televizorlar",
  },
  {
    id: "tv10",
    name: "Panasonic TX-55JZ",
    price: 1299,
    image: "/images/Panasonic TX-55JZ.webp",
    description: "Netflix Calibrated Mode dəstəyi.",
    category: "televizorlar",
  },
];
